/home/zcw7438/.local/lib/python3.6/site-packages/pandas/compat/_optional.py:106: UserWarning: Pandas requires version '1.2.1' or newer of 'bottleneck' (version '1.2.0' currently installed).
  warnings.warn(msg, UserWarning)
/home/zcw7438/.local/lib/python3.6/site-packages/pandas/compat/_optional.py:106: UserWarning: Pandas requires version '2.6.2' or newer of 'numexpr' (version '2.6.1' currently installed).
  warnings.warn(msg, UserWarning)
Traceback (most recent call last):
  File "/home/zcw7438/.local/lib/python3.6/site-packages/pandas/core/ops/__init__.py", line 968, in na_op
    result = expressions.evaluate(op, str_rep, x, y, **eval_kwargs)
  File "/home/zcw7438/.local/lib/python3.6/site-packages/pandas/core/computation/expressions.py", line 221, in evaluate
    return _evaluate(op, op_str, a, b, **eval_kwargs)
  File "/home/zcw7438/.local/lib/python3.6/site-packages/pandas/core/computation/expressions.py", line 70, in _evaluate_standard
    return op(a, b)
TypeError: must be str, not int

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "preModelData.py", line 74, in <module>
    preModelData(products, quarterOrMonth, mergingyear, mergingquarterormonth, involvedcompanies)
  File "preModelData.py", line 19, in preModelData
    market_size = marketSize(products, quarterOrMonth)
  File "preModelData.py", line 12, in marketSize
    market_size = market_size.add(market_size_product, fill_value=0)
  File "/home/zcw7438/.local/lib/python3.6/site-packages/pandas/core/ops/__init__.py", line 1493, in f
    return self._combine_frame(other, pass_op, fill_value, level)
  File "/home/zcw7438/.local/lib/python3.6/site-packages/pandas/core/frame.py", line 5386, in _combine_frame
    return ops.dispatch_to_series(this, other, _arith_op)
  File "/home/zcw7438/.local/lib/python3.6/site-packages/pandas/core/ops/__init__.py", line 596, in dispatch_to_series
    new_data = expressions.evaluate(column_op, str_rep, left, right)
  File "/home/zcw7438/.local/lib/python3.6/site-packages/pandas/core/computation/expressions.py", line 221, in evaluate
    return _evaluate(op, op_str, a, b, **eval_kwargs)
  File "/home/zcw7438/.local/lib/python3.6/site-packages/pandas/core/computation/expressions.py", line 70, in _evaluate_standard
    return op(a, b)
  File "/home/zcw7438/.local/lib/python3.6/site-packages/pandas/core/ops/__init__.py", line 576, in column_op
    return {i: func(a.iloc[:, i], b.iloc[:, i]) for i in range(len(a.columns))}
  File "/home/zcw7438/.local/lib/python3.6/site-packages/pandas/core/ops/__init__.py", line 576, in <dictcomp>
    return {i: func(a.iloc[:, i], b.iloc[:, i]) for i in range(len(a.columns))}
  File "/home/zcw7438/.local/lib/python3.6/site-packages/pandas/core/frame.py", line 5382, in _arith_op
    return func(left, right)
  File "/home/zcw7438/.local/lib/python3.6/site-packages/pandas/core/ops/__init__.py", line 1048, in wrapper
    result = na_op(lvalues, rvalues)
  File "/home/zcw7438/.local/lib/python3.6/site-packages/pandas/core/ops/__init__.py", line 970, in na_op
    result = masked_arith_op(x, y, op)
  File "/home/zcw7438/.local/lib/python3.6/site-packages/pandas/core/ops/__init__.py", line 447, in masked_arith_op
    result[mask] = op(xrav[mask], com.values_from_object(yrav[mask]))
TypeError: must be str, not int
